name: "OpenCart Documentation"
description: "Documentation for the OpenCart script from www.opencart.com"
url: "http://chris-wm.github.io/"
baseurl: "http://chris-wm.github.io/"
markdown: rdiscount
permalink: pretty